name: Rust

on:
  push:
    branches: ["main"]
    paths:
      - "chemu8_core/**"
      - "chemu8_desktop/**"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-desktop:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: x86_64
            runner: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev autoconf autoconf-archive automake libtool libltdl-dev
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            libx11-dev libxext-dev libxrandr-dev libxinerama-dev \
            libxcursor-dev libxi-dev libxss-dev libxxf86vm-dev \
            libwayland-dev wayland-protocols libxkbcommon-dev libdecor-0-dev \
            libegl1-mesa-dev libgl1-mesa-dev libgbm-dev \
            libasound2-dev libpulse-dev libudev-dev libdbus-1-dev

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            chemu8_core/target
            chemu8_desktop/target
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          cd chemu8_desktop
          cargo install cargo-vcpkg
          cargo vcpkg build
          cargo build --verbose --features "static-link use-vcpkg" --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: chemu8_desktop-linux-${{ matrix.platform.name }}
          path: chemu8_desktop/target/release/chemu8_desktop
          compression-level: 9

  build-desktop-macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: x86_64
            runner: macOS-26-intel
          - name: arm64
            runner: macOS-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            chemu8_core/target
            chemu8_desktop/target
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          cd chemu8_desktop
          cargo install cargo-vcpkg
          cargo vcpkg build
          cargo build --verbose --features "static-link use-vcpkg" --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: chemu8_desktop-macos-${{ matrix.platform.name }}
          path: chemu8_desktop/target/release/chemu8_desktop
          compression-level: 9

  build-desktop-windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: x86_64
            runner: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            chemu8_core/target
            chemu8_desktop/target
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          cd chemu8_desktop
          cargo install cargo-vcpkg
          cargo vcpkg build
          cargo build --verbose --features "static-link use-vcpkg" --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: chemu8_desktop-windows-${{ matrix.platform.name }}
          path: chemu8_desktop/target/release/chemu8_desktop.exe
          compression-level: 9
