name: Deploy Worker

on:
  push:
    branches: ["main"]
    paths:
      - "chemu8_core/**"
      - "chemu8_wasm/**"
      - "web/**"
      - ".github/workflows/web.yml"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            chemu8_core/target
            chemu8_wasm/target
            chemu8_wasm/pkg
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-web-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust WASM
        run: |
          cd chemu8_wasm
          cargo install wasm-pack
          ~/.cargo/bin/wasm-pack build -- --no-default-features

      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          version: "^11.23.0"
          cache: false
          cache-dependency-path: "web/pnpm-lock.yaml"
          package-json-file: "web/package.json"
          install: false

      - name: Install Frontend Dependencies
        run: |
          cd web
          pnpm install --frozen-lockfile

      - name: Build (Cloudflare)
        run: |
          cd web
          pnpm run build

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "web"

      - name: Build (GitHub Pages)
        run: |
          cd web
          VITE_BASE_PATH="/Chemu8/" pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
